import { useEffect, useState } from 'react'
import { Brand } from '../components/Brand.jsx'
import artwork from '../assets/concord-artwork-original.png'
import artworkSmall from '../assets/concord-artwork-640.png'

export function LandingPage({ user, navigate }) {
  const [menuOpen, setMenuOpen] = useState(false)
  const [demoMessage, setDemoMessage] = useState(0)
  useEffect(() => {
    const timer = setInterval(() => setDemoMessage(value => (value + 1) % 3), 2800)
    return () => clearInterval(timer)
  }, [])
  const openApp = () => navigate(user ? '/app' : '/login')
  return <div className="landing-page">
    <header className="landing-nav"><button className="brand-button" onClick={() => navigate('/')}><Brand /></button><button className="nav-toggle" aria-label="Abrir menu" aria-expanded={menuOpen} onClick={() => setMenuOpen(value => !value)}>☰</button><nav className={menuOpen ? 'open' : ''} aria-label="Navegação principal"><a href="#recursos">Recursos</a><a href="#comunidades">Comunidades</a><a href="#seguranca">Segurança</a><a href="#sobre">Sobre</a></nav><div className="nav-actions">{user ? <button className="nav-user" onClick={() => navigate('/app')}>{user.username}</button> : <button className="nav-login" onClick={() => navigate('/login')}>Entrar</button>}<button className="landing-primary compact" onClick={openApp}>Abrir Concord</button></div></header>
    <main><section className="landing-hero"><div className="hero-copy"><span className="landing-kicker">COMUNIDADES EM TEMPO REAL</span><h1>Seu espaço.<br />Sua comunidade.<br /><em>Sua voz.</em></h1><p>Reúna pessoas em servidores próprios, converse em canais organizados e entre em salas de voz instantaneamente.</p><div className="landing-actions"><button className="landing-primary" onClick={openApp}>Abrir Concord <span>→</span></button>{!user && <button className="landing-secondary" onClick={() => navigate('/register')}>Criar uma conta</button>}</div><div className="hero-proof"><span><b>●</b> Chat em tempo real</span><span><b>●</b> Voz com WebRTC</span><span><b>●</b> Comunidades próprias</span></div></div><div className="hero-visual"><picture><source media="(max-width: 700px)" srcSet={artworkSmall}/><img className="hero-artwork" src={artwork} alt="Raposa digital vermelha, arte oficial do Concord" fetchPriority="high"/></picture><ConcordDemo step={demoMessage} /></div></section>
      <section className="landing-section chat-showcase" id="recursos"><div><span className="section-number">01 / CHAT</span><h2>Conversas que acompanham o seu ritmo.</h2><p>Mensagens chegam no instante certo. Presença, typing e canais deixam cada conversa clara, viva e organizada.</p></div><div className="feature-window"><header><span>#</span><strong>projeto-orbita</strong><i>8 online</i></header><div className="feature-messages"><DemoLine initials="MA" name="Marina" text="A nova direção está pronta para revisão." /><DemoLine initials="DV" name="Davi" text="Entrando agora. Vamos fechar isso juntos." active /><div className="typing-demo"><i/><i/><i/> Aurora está digitando</div></div></div></section>
      <section className="landing-section voice-showcase"><div className="voice-orbit"><span className="orbit-core">VOZ<br/><b>AO VIVO</b></span>{['AL','MR','DV','KN'].map((name,index)=><span className={`orbit-user orbit-${index+1}`} key={name}>{name}{index===0&&<i/>}</span>)}</div><div><span className="section-number">02 / VOZ</span><h2>Entre na conversa. Sem ligar para ninguém.</h2><p>Clique em um canal e esteja junto. Controle microfone, áudio e volume individual enquanto o WebRTC mantém a voz entre participantes.</p><ul><li>Entrada e saída instantâneas</li><li>Mute, deafen e volume individual</li><li>Indicador de quem está falando</li></ul></div></section>
      <section className="community-section" id="comunidades"><span className="section-number">03 / COMUNIDADES</span><h2>Uma casa digital construída por você.</h2><div className="community-grid"><FeatureCard icon="◇" title="Servidores" text="Espaços independentes para cada equipe, grupo ou comunidade."/><FeatureCard icon="#" title="Canais" text="Organize texto e voz por assunto, projeto ou momento."/><FeatureCard icon="◎" title="Membros" text="Convites, papéis e administração para crescer com controle."/></div></section>
      <section className="security-section" id="seguranca"><div><span className="section-number">SEGURANÇA</span><h2>Sua comunidade, protegida desde a base.</h2></div><p>Autenticação JWT, permissões no servidor e sinalização de voz autorizada. O áudio não passa pelo backend do Concord.</p></section>
      <section className="final-cta" id="sobre"><Brand compact/><h2>Pronto para entrar no Concord?</h2><p>Crie seu espaço e transforme presença em conexão.</p><div className="landing-actions"><button className="landing-primary" onClick={openApp}>Abrir Concord</button>{!user&&<button className="landing-secondary" onClick={()=>navigate('/register')}>Criar conta</button>}</div></section>
    </main><footer className="landing-footer"><Brand/><span>Comunidades · Chat · Voz em tempo real</span><a href="https://github.com/xavierr-max/concord-mock" target="_blank" rel="noreferrer">GitHub ↗</a><small>© {new Date().getFullYear()} Concord</small></footer>
  </div>
}

function ConcordDemo({ step }) { return <div className="concord-demo" aria-label="Demonstração visual do Concord"><div className="demo-servers"><b>C</b><i/><i/><i/><button>＋</button></div><div className="demo-channels"><strong>NÚCLEO CRIATIVO</strong><small>CANAIS DE TEXTO</small><span className="selected"># projeto-orbita</span><span># referências</span><small>CANAIS DE VOZ</small><span>◖)) Sala de criação</span><div className="demo-voice"><i className="speaking">AL</i><i>DV</i><i>MR</i><b>3 conectados</b></div></div><div className="demo-chat"><header><b># projeto-orbita</b><span>Transformando ideias em algo real.</span></header><div className="demo-chat-body"><div className="demo-welcome"><b>#</b><h3>projeto-orbita</h3><p>O começo de uma grande ideia.</p></div><DemoLine initials="AL" name="Aurora" text="A identidade está ficando incrível." active={step===0}/><DemoLine initials="MR" name="Marcos" text="Acabei de entrar no canal de voz." active={step===1}/>{step===2&&<div className="demo-new-message"><b>DV</b><span><strong>Davi</strong> Vamos testar juntos agora.</span></div>}</div><div className="demo-composer">Mensagem para #projeto-orbita <b>＋</b></div></div></div> }
function DemoLine({ initials,name,text,active=false }) { return <div className={`demo-line ${active?'active':''}`}><b>{initials}</b><span><strong>{name}</strong><p>{text}</p></span></div> }
function FeatureCard({icon,title,text}) { return <article><i>{icon}</i><h3>{title}</h3><p>{text}</p><span>Explorar →</span></article> }
